# config-microservices-cloud/producto.yml
server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://soa.c904q64o6yfq.us-east-2.rds.amazonaws.com:5432/soa
    username: postgres
    password: Admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true